argo-cd:
  global:
    domain: argocd.local

  configs:
    cm:
      exec.enabled: true
    params:
      dexserver.disable.tls: true
      server.insecure: true
      server.enable.proxy.extension: true
    exec.enabled: true
    resource.exclusions: |
      - apiGroups:
          - kyverno.io
        kinds:
          - AdmissionReport
          - BackgroundScanReport
          - ClusterAdmissionReport
          - ClusterBackgroundScanReport
        clusters:
          - '*'

  redis-ha:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 1
    extensions:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: ""
      hosts:
        - argocd.local
      # extraHosts:
      #   - argocd.local
      paths:
        - /
      pathType: Prefix
      extraPaths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argo-argocd-server
              port:
                number: 80
      tls:
        []
      https: false
    

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1