argo-cd:
  global:
    domain: argocd.local
  redis-ha:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 1
    extensions:
      enabled: true
    config:
      params:
        server.insecure: true
      exec.enabled: true
      resource.exclusions: |
        - apiGroups:
            - kyverno.io
          kinds:
            - AdmissionReport
            - BackgroundScanReport
            - ClusterAdmissionReport
            - ClusterBackgroundScanReport
          clusters:
            - '*'
    ingress:
      enabled: true
      ingressClassName: ""
      # extraHosts:
      #   - argocd.local
      paths:
        - /
      pathType: Prefix
      extraPaths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argo-argocd-server
              port:
                number: 80
      tls:
        []
      https: false
    

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1