apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green
  namespace: argocd
spec:
  project: default
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/SantiEeich/self-managed-argo
    targetRevision: HEAD
    path: "apps/blue-green"
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - enableDryRun=true